<a href="https://colab.research.google.com/github/asmit-ayank/UCS420/blob/main/Assignment%204/Assignment_4_UCS420.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

**ASSIGNMENT 4**

**Asmit Ayank**

**102497002**



Q.1 Write a program to create a NumPy 1D-array with 5 elements and perform basic
operations like:

a) Addition of 2 in all the element
b) Multiply 3 with all the elements
c) Divide every element by 2

In [1]:
import numpy as np
arr = np.array([1, 2, 3, 4, 5])
add_arr = arr + 2
mult_arr = arr * 3
div_arr = arr / 2

print("Original Array:", arr)
print("After Addition:", add_arr)
print("After Multiplication:", mult_arr)
print("After Division:", div_arr)

Original Array: [1 2 3 4 5]
After Addition: [3 4 5 6 7]
After Multiplication: [ 3  6  9 12 15]
After Division: [0.5 1.  1.5 2.  2.5]


Q.2 Questions on Basic NumPy Array:

a) Reverse the NumPy array: arr = np.array([1, 2, 3, 6, 4, 5])
b) Find the most frequent value and their indice(s) in the following arrays:
i. x = np.array([1,2,3,4,5,1,2,1,1,1])
ii. y = np.array([1, 1, 1, 2, 3, 4, 2, 4, 3, 3, ])

In [2]:
arr = np.array([1, 2, 3, 4, 5])
import numpy as np
res = np.flip(arr)

print("(a) Final reversed array: ", res)
x = np.array([1, 2, 3, 4, 5, 1, 2, 1, 1, 1])
y = np.array([1, 1, 1, 2, 3, 4, 2, 4, 3, 3])
def most_frequent(arr):
    unique, counts = np.unique(arr, return_counts=True)
    most_freq = unique[np.argmax(counts)]
    indices = np.where(arr == most_freq)[0]
    return most_freq, indices
freq_x, indices_x = most_frequent(x)
freq_y, indices_y = most_frequent(y)
print("(b)");
print("(i) Most Frequent in x:", freq_x, "at indices", indices_x)
print("(ii) Most Frequent in y:", freq_y, "at indices", indices_y)

(a) Final reversed array:  [5 4 3 2 1]
(b)
(i) Most Frequent in x: 1 at indices [0 5 7 8 9]
(ii) Most Frequent in y: 1 at indices [0 1 2]


Q.3 For the given 2-D array arr=np.array([10, 20, 30], [40, 50, 60], [70, 80, 90]), access
elements using row and column indices as follows:

a) Access 1st row, 2nd column
b) Access 3rd row, 1st column

In [3]:
arr = np.array([[10, 20, 30], [40, 50, 60], [70, 80, 90]])
element1 = arr[0, 1]
element2 = arr[2, 0]

print("(a) Element at (1st row, 2nd column):", element1)
print("(b) Element at (3rd row, 1st column):", element2)

(a) Element at (1st row, 2nd column): 20
(b) Element at (3rd row, 1st column): 70


Q.4 Write program to create an 1-D NumPy array named <<Your Name>> with evenly
spaced 25 numbers from 10 to 100 using linspace(). Print the dimensions of the array,
shape, total elements, the data type of each element and total number of bytes consumed
by the array. Find the transpose of this array using reshape() attribute. Can we do the same
with T attribute?

In [4]:
asmit = np.linspace(10, 100, 25)


print("Array:", asmit)
print("Dimensions:", asmit.ndim)
print("Shape:", asmit.shape)
print("Total Elements:", asmit.size)
print("Data Type of Elements:", asmit.dtype)
print("Total Bytes Consumed:", asmit.nbytes)
asmit_transposed = asmit.reshape(25, 1)
print("\nTransposed using reshape():\n", asmit_transposed)


asmit_t = asmit.T
print("\nTransposed using T attribute:", asmit_t)
print("Shape after T attribute:", asmit_t.shape)

Array: [ 10.    13.75  17.5   21.25  25.    28.75  32.5   36.25  40.    43.75
  47.5   51.25  55.    58.75  62.5   66.25  70.    73.75  77.5   81.25
  85.    88.75  92.5   96.25 100.  ]
Dimensions: 1
Shape: (25,)
Total Elements: 25
Data Type of Elements: float64
Total Bytes Consumed: 200

Transposed using reshape():
 [[ 10.  ]
 [ 13.75]
 [ 17.5 ]
 [ 21.25]
 [ 25.  ]
 [ 28.75]
 [ 32.5 ]
 [ 36.25]
 [ 40.  ]
 [ 43.75]
 [ 47.5 ]
 [ 51.25]
 [ 55.  ]
 [ 58.75]
 [ 62.5 ]
 [ 66.25]
 [ 70.  ]
 [ 73.75]
 [ 77.5 ]
 [ 81.25]
 [ 85.  ]
 [ 88.75]
 [ 92.5 ]
 [ 96.25]
 [100.  ]]

Transposed using T attribute: [ 10.    13.75  17.5   21.25  25.    28.75  32.5   36.25  40.    43.75
  47.5   51.25  55.    58.75  62.5   66.25  70.    73.75  77.5   81.25
  85.    88.75  92.5   96.25 100.  ]
Shape after T attribute: (25,)


Q5. Create a 2-D Array of three rows and four columns, named ucs420_<your_name>>
with following values – 10, 20, 30, 40, 50, 60, 70, 80, 90, 15, 20, 35. Compute the mean,
median, max, min, unique elements. Reshape the array to four rows and three columns and
name it as reshaped_ ucs420_<your_name>>. Resize the array to two rows and three
columns and name it as resized_ ucs420_<your_name>>.

In [7]:
ucs420_asmit = np.array([[10, 20, 30, 40], [50, 60, 70, 80], [90, 15, 20, 35]])

print("\nMean:", np.mean(ucs420_asmit))
print("Median:", np.median(ucs420_asmit))
print("Max:", np.max(ucs420_asmit))
print("Min:", np.min(ucs420_asmit))
print("Unique Elements:", np.unique(ucs420_asmit))

reshaped_ucs420_asmit = ucs420_asmit.reshape(4, 3)
print("\nReshaped Array (4x3):\n", reshaped_ucs420_asmit)


resized_ucs420_asmit = np.resize(ucs420_asmit, (2, 3))
print("\nResized Array (2x3):\n", resized_ucs420_asmit)


Mean: 43.333333333333336
Median: 37.5
Max: 90
Min: 10
Unique Elements: [10 15 20 30 35 40 50 60 70 80 90]

Reshaped Array (4x3):
 [[10 20 30]
 [40 50 60]
 [70 80 90]
 [15 20 35]]

Resized Array (2x3):
 [[10 20 30]
 [40 50 60]]
